kind: pipeline
type: kubernetes
name: Init

node_selector:
  eks.amazonaws.com/nodegroup: automation
trigger:
  event:
    - push

steps:
  - name: Bump patch version
    pull: if-not-exists
    image: 221581667315.dkr.ecr.eu-west-1.amazonaws.com/deel-devops/nodeawscli:16.1
    commands:
      - npm version patch --commit-hooks=false -m "[CI SKIP] Automatically bumped version to %s" --force

    environment:
      NODE_AUTH_TOKEN:
        from_secret: git_pat

  - name: build npm package for init
    pull: if-not-exists
    image: 221581667315.dkr.ecr.eu-west-1.amazonaws.com/ecr-public/bitnami/node:16
    commands:
      - npm install

  - name: push new version to git
    pull: if-not-exists
    image: 221581667315.dkr.ecr.eu-west-1.amazonaws.com/deel-devops/nodeawscli:16.1
    commands:
      - git config --global url."https://$${NODE_AUTH_TOKEN}@github".insteadOf https://github
      - git push --set-upstream origin ${CI_COMMIT_BRANCH}
    environment:
      NODE_AUTH_TOKEN:
        from_secret: git_pat

  - name: publish package to codeartifact
    pull: if-not-exists
    image: 221581667315.dkr.ecr.eu-west-1.amazonaws.com/deel-devops/nodeawscli:16.1
    commands:
      - aws codeartifact login --tool npm --repository npm-dev --domain npm --domain-owner 221581667315
      - echo "registry=https://npm-221581667315.d.codeartifact.eu-west-1.amazonaws.com/npm/npm-dev/" > .npmrc
      - echo "npm-221581667315.d.codeartifact.eu-west-1.amazonaws.com/npm/npm-dev/:always-auth=true" >> .npmrc
      - npm publish
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-1
---
kind: secret
name: AWS_ACCESS_KEY_ID
get:
  path: drone
  name: aws-access-key-id
---
kind: secret
name: AWS_SECRET_ACCESS_KEY
get:
  path: drone
  name: aws-secret-access-key
---
kind: secret
name: git_pat
get:
  path: drone
  name: git_pat